### ISSUE TITLE
KMS decrypt example

### ISSUE THREAD

**Issue by samuaz** [awsdocs/aws-cpp-developer-guide#17]
Hello!

im trying to found any example to how decrypt a password encrypted by KMS, for example i have a RDS database password encrypted by KMS, i want to decrypt it in my aws-cpp-lambda function to connect to the database.

i see that for call client Decrypt i need a DecryptRequest;
but i don't know how to initialize it and where set my "encriptedPassword" in the DecryptedRequest to call client.Decrypt()

this is base64
encriptedPassword = "GPK0ujdAAAAZzBlBgkqhkiG"
```

Aws::SDKOptions options;
InitAPI(options);
    {
        Aws::Client::ClientConfiguration awsConfig;
        awsConfig.region = Aws::Environment::GetEnv("AWS_REGION");
        Aws::KMS::KMSClient client(awsConfig);

 
  //      Aws::KMS::Model::DecryptRequest decryptRequest;
   //     client.Decrypt(decryptRequest);

    }
    // shutdown the aws api
    std::cout << "shutdown api" << "\n";
    ShutdownAPI(options);

```

anyone cant write a small example please. Thanks to all!!

**Comment by SCalwas** [comment]
Pass your encrypted data key in the `DecryptRequest.SetCiphertextBlob()` method. The decrypted key will be returned in the `DecryptResult.GetPlaintext()` method.

I recently wrote an example in Python that walks through the entire encryption/decryption process, but have not yet translated it to C++. If you need more details, perhaps the Python example will help. It's described at https://boto3.amazonaws.com/v1/documentation/api/latest/guide/kms-example-encrypt-decrypt-file.html

**Comment by samuaz** [comment]
@SCalwas thanks for answer

so if i do:
 ```
        Aws::KMS::KMSClient client(awsConfig);
        Aws::KMS::Model::DecryptRequest decryptRequest;
        unsigned char * password = (unsigned char *) env->getDB_PASSWORD().c_str();
        Aws::Utils::CryptoBuffer buffer(password, size_t(password));
        decryptRequest.SetCiphertextBlob(buffer);
        auto decryptResult = client.Decrypt(decryptRequest);

       // and this shouldbe my password, i see this return a buffer, later i need to convert to string
        decryptResult.GetResult().GetPlaintext();
```

let me try!!

**Comment by SCalwas** [comment]
I can't verify all the details about retrieving and converting your password--those operations are specific to your app--but the SetCiphertextBlob/Decrypt/GetPlaintext sequence will decrypt your encrypted string.
