### ISSUE TITLE
NuGet packages no longer supported by the C++ SDK

### ISSUE THREAD

**Issue by KaibaLopez** [awsdocs/aws-cpp-developer-guide#38]
The C++ SDK team no longer supports NuGet packages as a way to install the SDK, so it should be removed from the [Setting Up the AWS SDK for C++](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup.html) section of the developer guide.

**Comment by KaibaLopez** [comment]
For reference, this was brought up to us through this [issue](https://github.com/aws/aws-sdk-cpp/issues/1393).

**Comment by ghost** [comment]
Confirmed with C++ SDK team that NuGet is supported through SDK version 1.6 and with Microsoft Visual Studio versions 2015 and 2017. Updated the aforementioned section with this information.
