### ISSUE TITLE
Building Your Application with CMake - unknown feature "cxx_std_11"

### ISSUE THREAD

**Issue by rvernica** [awsdocs/aws-cpp-developer-guide#39]
See: https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/build-cmake.html

The `CMakeLists.txt` file contains:
```
cmake_minimum_required(VERSION 3.2)
...
target_compile_features(my-example PUBLIC cxx_std_11)
```

My understanding is that `cxx_std_11` was introduced in CMake `3.8`. So, a minimum CMake version of `3.2` and `cxx_std_11` don't work together.

**Comment by ghost** [comment]
Sorry for the delayed response. Thanks for catching this. I will bring this to the attention of the AWS SDK for C++ team and see about a possible fix.

**Comment by ghost** [comment]
I've confirmed that 3.2 should indeed be changed to 3.8. I'm making the fix now. Again, thanks for catching this.
