### ISSUE TITLE
typo in variable creation and initialisation (:=) 

### ISSUE THREAD

**Issue by jespada** [awsdocs/aws-cpp-developer-guide#5]
In [common-examples](https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/common-examples.html) under the section _Create a New Bucket and Object_ there is a missing colon in:

```
uploadResult, err = svc.PutObject(&s3.PutObjectInput{...
```

 it should be:

```
uploadResult, err := svc.PutObject(&s3.PutObjectInput{...
```

**Comment by EronHennessey** [comment]
The referenced page is in the _Go SDK Developer Guide_... the repo for that is here:
- https://github.com/awsdocs/aws-go-developer-guide

The sample in that topic is pulled from here:
- https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/go/example_code/s3/create_new_bucket_and_object.go

I've [fixed it in the code](https://github.com/awsdocs/aws-doc-sdk-examples/commit/48891a1c8e3587c9510a722d253691136e082f73). I'll let the writer know to republish the docs with the fix.

Thanks!
